version: '3.3'
services:
    dispatch_server:
        build: .
        labels:
            - "traefik.enable=true"
            # https
            - "traefik.http.routers.dispatchoriginal_server_https.rule=Host(`dispatchoriginal.schoff.it`)"
            - "traefik.http.routers.dispatchoriginal_server_https.entrypoints=websecure"
            - "traefik.http.routers.dispatchoriginal_server_https.tls.certresolver=letsencrypt"
            - "traefik.http.services.dispatchoriginal_server_https.loadbalancer.server.port=80"
        networks:
            - traefik

networks:
  traefik:
    external:
      name: traefik
