version: '3.3'
services:
    dispatch_server:
        image: .
        labels:
            - "traefik.enable=true"
            # https
            - "traefik.http.routers.dispatch_server_https.rule=Host(`dispatch.schoff.it`)"
            - "traefik.http.routers.dispatch_server_https.entrypoints=websecure"
            - "traefik.http.routers.dispatch_server_https.tls.certresolver=letsencrypt"
            - "traefik.http.services.dispatch_server_https.loadbalancer.server.port=3000"
        networks:
            - traefik

networks:
  traefik:
    external:
      name: traefik
